[Service]
Environment="HTTP_PROXY={{ .Values.cluster.proxy.httpProxy }}"
Environment="HTTPS_PROXY={{ .Values.cluster.proxy.httpsProxy }}"
Environment="NO_PROXY={{ .Values.cluster.proxy.noProxy }}"
Environment="http_proxy={{ .Values.cluster.proxy.httpProxy }}"
Environment="https_proxy={{ .Values.cluster.proxy.httpsProxy }}"
Environment="no_proxy={{ .Values.cluster.proxy.noProxy }}"
