---
# Source: gpu-node-pool/templates/karpentermachinepool.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KarpenterMachinePool
metadata:
  name: test-wc-gpu00
  namespace: org-giantswarm
  labels:
    app: "gpu-node-pool"
    app.kubernetes.io/name: "gpu-node-pool"
    app.kubernetes.io/instance: "test-wc-gpu00"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "0.0.1"
    application.giantswarm.io/team: "bumblebee"
    helm.sh/chart: "gpu-node-pool-0.0.0-dev"
    cluster.x-k8s.io/cluster-name: "test-wc"
    cluster.x-k8s.io/watch-filter: capi
    giantswarm.io/cluster: "test-wc"
    giantswarm.io/machine-pool: "test-wc-gpu00"
    giantswarm.io/organization: "giantswarm"
spec:
  ec2NodeClass:
    amiSelectorTerms:
    - name: flatcar-stable-4593.2.5-kube-1.33.1-tooling-1.27.0-gs
      owner: "706635527432"
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        volumeSize: 15Gi
        volumeType: gp3
      rootVolume: true
    - deviceName: /dev/xvde
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 30Gi
        volumeType: gp3
    instanceProfile: test-wc-worker
    instanceStorePolicy: RAID0
    metadataOptions:
      httpPutResponseHopLimit: 3
      httpTokens: required
    securityGroupSelectorTerms:
    - tags:
        sigs.k8s.io/cluster-api-provider-aws/cluster/test-wc: owned
        sigs.k8s.io/cluster-api-provider-aws/role: node
    - tags:
        sigs.k8s.io/cluster-api-provider-aws/cluster/test-wc: owned
        sigs.k8s.io/cluster-api-provider-aws/role: lb
    subnetSelectorTerms:
    - tags:
        giantswarm.io/role: nodes
        sigs.k8s.io/cluster-api-provider-aws/cluster/test-wc: owned
    tags:
      Name: test-wc-gpu00
  nodePool:
    disruption:
      consolidationPolicy: WhenEmptyOrUnderutilized
      consolidateAfter: 10m
    limits:
      nvidia.com/gpu: "4"
    template:
      metadata:
        labels:
          giantswarm.io/machine-pool: test-wc-gpu00
      spec:
        requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
          - g6
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
          - xlarge
          - 2xlarge
          - 4xlarge
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - eu-central-1b
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - on-demand
        startupTaints:
        - effect: NoSchedule
          key: node.cluster.x-k8s.io/uninitialized
          value: "true"
        - effect: NoSchedule
          key: node.cilium.io/agent-not-ready
          value: "true"
        - effect: NoExecute
          key: ebs.csi.aws.com/agent-not-ready
          value: "true"
        taints:
        - effect: NoSchedule
          key: nvidia.com/gpu
        terminationGracePeriod: 30m
